### ISSUE TITLE
Write up Lesson Plan for Week 3 - Functions

### ISSUE THREAD

**Issue by dskamiotis** [guardian/typescript-school#6]
Refer to Slideshow  [here](https://docs.google.com/presentation/d/150b7CKHA-s9NQ05GWXzrgEAk2lyuikbO2la6TklFaEw/edit#slide=id.g256b012de15_0_21) for handbook with examples setup

**Comment by georgeblahblah** [comment]
Completed in https://github.com/guardian/typescript-school/pull/32
